name: Merge dev to main

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Fetch all branches
        run: git fetch origin

      - name: Switch to main branch
        run: git checkout main

      - name: Merge dev into main
        run: git merge origin/dev --no-ff -m "Merge dev into main [automated]"

      - name: Push changes
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
